### PR TITLE
Update Sentry Link

### PR DESCRIPTION
**Pull request by RaghavPrabhakar66**
delete commandlinetools.zip also

### CODE REVIEW

**Review by MankaranSingh — APPROVED** [review]

**Comment by RaghavPrabhakar66** [comment]
> if you rerun the script, it errors out saying some folder already exists. can you fix that too ? the script shouldnt ever fail even if everythin is already setup

There are two ways to solve this:
1. Delete all existing directories such as ~/Android etc.
2. Or use something as the following
```bash
if ! [ -e ~/Android ]; then
    mkdir -p ~/Android/Sdk/cmdline-tools/latest
    mv cmdline-tools/* ~/Android/Sdk/cmdline-tools/latest/
    rm -rf cmdline-tools
else
    info "Skipping Android SDK installation as it is already installed."
fi
```
I think second solution is more elegant.

**Comment by MankaranSingh** [comment]
re-write info as `"Skipping Android SDK installation, ~/Android already exists"` and we merge

**Comment by RaghavPrabhakar66** [comment]
@MankaranSingh done.

**Comment by MankaranSingh** [comment]
This version of sentry is pip installable on termux ?

**Comment by RaghavPrabhakar66** [comment]
yeah

**Comment by MankaranSingh** [comment]
added manually

**Pull request closed without merging**
